name: Unit Tests
on:
  pull_request:
    types: [ready_for_review, opened, synchronize, reopened]

jobs:
  build:
    name: Unit Tests
    runs-on: macOS-latest
    if: github.event.pull_request.draft == false
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      DEVELOPER_DIR: '/Applications/Xcode_11.6.app/Contents/Developer'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Build
      run: swift build -v

    - name: Test
      run: swift test -v
